// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "cytoUtils_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// getDescendants
VertexID_vec getDescendants(Rcpp::XPtr<GatingSet> gsPtr, string sampleName, string node);
RcppExport SEXP cytoUtils_getDescendants(SEXP gsPtrSEXP, SEXP sampleNameSEXP, SEXP nodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<GatingSet> >::type gsPtr(gsPtrSEXP);
    Rcpp::traits::input_parameter< string >::type sampleName(sampleNameSEXP);
    Rcpp::traits::input_parameter< string >::type node(nodeSEXP);
    rcpp_result_gen = Rcpp::wrap(getDescendants(gsPtr, sampleName, node));
    return rcpp_result_gen;
END_RCPP
}
