# Generated by cpp11: do not edit by hand

getTautStringApprox <- function(dataVec) {
  .Call(`_cytoUtils_getTautStringApprox`, dataVec)
}

singleDip <- function(x) {
  .Call(`_cytoUtils_singleDip`, x)
}

tsGates <- function(xVec, modePrior) {
  .Call(`_cytoUtils_tsGates`, xVec, modePrior)
}
