# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' grab all the descendant nodes for a given node
#'
#' This is a faster version of flowIncubator:::getDescendants
#'
#' @param gsPtr external pointer that points to the C data structure of GatingSet
#' @param sampleName sample name
#' @param node node name
.getDescendants <- function(gsPtr, sampleName, node) {
    .Call('cytoUtils_getDescendants', PACKAGE = 'cytoUtils', gsPtr, sampleName, node)
}

